name: Merge DEB chunks
on:
  push:
    paths:
      - 'repo/debs/newpart_*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge chunks and cleanup
        run: |
          cat repo/debs/newpart_aa repo/debs/newpart_ab repo/debs/newpart_ac repo/debs/newpart_ad > repo/debs/com.kiloo.subwaysurfers_1.86.0-4_iphoneos-arm.deb
          rm -f repo/debs/newpart_*
          rm -f repo/debs/deb.part_*
          ls -la repo/debs/
      - name: Commit merged deb
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo/debs/
          git commit -m "Merge new deb chunks, remove old parts" || echo "No changes"
          git push
